index:
    path: /
    controller: App\Controller\MainController::homepage


# Categories
category_page:
    path: /kategoria/{slug}-k{id}
    controller: App\Controller\CategoryController::categoryPage
    requirements:
        id: \d+
        slug: .*

categories_all:
    path: /kategorie
    controller: App\Controller\CategoryController::categories

# Posts
post_page:
    path: /wpis/{slug}-w{id}
    controller: App\Controller\PostController::postPage
    requirements:
        id: \d+
        slug: .*

# Static

contact:
    path: /kontakt
    controller: App\Controller\ContactController::contact
